// js/seed-data.js
// Initial employee data loaded from the Excel sheet (Pixous ESI/PF Details — Perundurai).
// This is seed data: it is loaded into localStorage on first run only.
// After that, all changes (add / edit / delete / photos) live in localStorage.

window.SEED_DATA = [
  {
    "id": 1,
    "name": "Arif K",
    "fatherHusbandName": "Karthikeyan M",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "42C,Siva Complex,State Bank Nagar,Chettipalayam,Erode.",
    "qualification": "Diplamo(EEE)",
    "experience": "8years",
    "dob": "1998-10-17",
    "doj": "8 Apr , Wed",
    "pan": "HTTPK1776E",
    "aadhar": "428602962905",
    "uan": "",
    "mobile": "7339443444",
    "email": "arifsabi1730@gmail.com",
    "esiRegNo": "",
    "nomineeName": "Sabeena Banu",
    "nomineeAddress": "42C,Siva Complex,State Bank Nagar,Chettipalayam,Erode.",
    "nomineeRelation": "Wife",
    "nomineeDob": "1998-12-30",
    "familyMember": "Sabeena Banu",
    "familyRelation": "Wife",
    "familyDob": "1998-12-30",
    "familyAddress": "42C,Siva Complex,State Bank Nagar,Chettipalayam,Erode.",
    "bankName": "Axis Bank",
    "accountNo": "922010049646614",
    "ifsc": "UTIB0000785",
    "photo": null
  },
  {
    "id": 2,
    "name": "Dinesh S",
    "fatherHusbandName": "Selvaraj K",
    "gender": "Male",
    "maritalStatus": "Unmarried",
    "address": "22-1,Shanmuga Nagar,Vediyarasampalayam,Alamedu,Pallipalayam,Namakkal.",
    "qualification": "MBA",
    "experience": "1year",
    "dob": "2003-03-22",
    "doj": "6 Apr , Monday",
    "pan": "HAVPD3078K",
    "aadhar": "924914986337",
    "uan": "",
    "mobile": "6385514511",
    "email": "dinesh.smba2003@gmail.com",
    "esiRegNo": "",
    "nomineeName": "Selvaraj K",
    "nomineeAddress": "22-1,Shanmuga Nagar,Vediyarasampalayam,Alamedu,Pallipalayam,Namakkal.",
    "nomineeRelation": "Father",
    "nomineeDob": "1965-03-01",
    "familyMember": "Selvaraj K",
    "familyRelation": "Father",
    "familyDob": "1965-03-01",
    "familyAddress": "22-1,Shanmuga Nagar,Vediyarasampalayam,Alamedu,Pallipalayam,Namakkal.",
    "bankName": "Karur Visiya Bank",
    "accountNo": "1654155000098520",
    "ifsc": "KVBL0001654",
    "photo": null
  },
  {
    "id": 3,
    "name": "Dinesh R",
    "fatherHusbandName": "Rajamanikam S",
    "gender": "Male",
    "maritalStatus": "Unmarried",
    "address": "5/91-C,Nallagoundamapalayam,Anangur,Tiruchengode.",
    "qualification": "Diplamo(Textile)",
    "experience": "5years",
    "dob": "1997-05-21",
    "doj": "16,Apr",
    "pan": "FMZPR1737P",
    "aadhar": "962272864493",
    "uan": "",
    "mobile": "9500250212",
    "email": "dt7661300@gmail.com",
    "esiRegNo": "",
    "nomineeName": "Rajamanikam",
    "nomineeAddress": "5/91-C,Nallagoundamapalayam,Anangur,Tiruchengode.",
    "nomineeRelation": "Father",
    "nomineeDob": "",
    "familyMember": "Rajamanikam",
    "familyRelation": "Father",
    "familyDob": "",
    "familyAddress": "5/91-C,Nallagoundamapalayam,Anangur,Tiruchengode.",
    "bankName": "Indian Bank",
    "accountNo": "6849439766",
    "ifsc": "IDIB000A194",
    "photo": null
  },
  {
    "id": 4,
    "name": "Rajkumar S",
    "fatherHusbandName": "Selvaraj R",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "162/1A,Eraniyan Street,Manicka Vasakar Colony,Erode.",
    "qualification": "B.com",
    "experience": "20years",
    "dob": "1979-02-06",
    "doj": "8 Apr , Wed",
    "pan": "AIEPR9108A",
    "aadhar": "578699515379",
    "uan": "",
    "mobile": "8675118810",
    "email": "srajkumarerd@gamail.com",
    "esiRegNo": "",
    "nomineeName": "Dharaneesh",
    "nomineeAddress": "162/1A,Eraniyan Street,Manicka Vasakar Colony,Erode.",
    "nomineeRelation": "Son",
    "nomineeDob": "2007-11-20",
    "familyMember": "Dharaneesh",
    "familyRelation": "Son",
    "familyDob": "2007-11-20",
    "familyAddress": "162/1A,Eraniyan Street,Manicka Vasakar Colony,Erode.",
    "bankName": "State Bank of India",
    "accountNo": "38164349599",
    "ifsc": "SBIN0012779",
    "photo": null
  },
  {
    "id": 5,
    "name": "Chelladurai M",
    "fatherHusbandName": "Murugan",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "24-4,North Street,Poolampatti,Marichilambu,Dindigul.",
    "qualification": "SSLC",
    "experience": "2 Years",
    "dob": "1971-09-20",
    "doj": "13 Apr, Monday",
    "pan": "BWAPC5280K",
    "aadhar": "544309226282",
    "uan": "",
    "mobile": "9751301797",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Menaga",
    "nomineeAddress": "24-4,North Street,Poolampatti,Marichilambu,Dindigul.",
    "nomineeRelation": "Wife",
    "nomineeDob": "1980-08-01",
    "familyMember": "Menaga",
    "familyRelation": "Wife",
    "familyDob": "1980-08-01",
    "familyAddress": "24-4,North Street,Poolampatti,Marichilambu,Dindigul.",
    "bankName": "Indian Overseas Bank",
    "accountNo": "183201000017716",
    "ifsc": "IOBA0001832",
    "photo": null
  },
  {
    "id": 6,
    "name": "Subramani P V",
    "fatherHusbandName": "Venkatachalam",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "228,1010 Nesavalar Colony,Mukasipidariyur,Erode.",
    "qualification": "8th Std",
    "experience": "1Year",
    "dob": "1959-06-09",
    "doj": "6 Apr , Monday",
    "pan": "GQKPS9569G",
    "aadhar": "449265315390",
    "uan": "",
    "mobile": "9095291263",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "S.Gowthaman",
    "nomineeAddress": "228,1010 Nesavalar Colony,Mukasipidariyur,Erode.",
    "nomineeRelation": "Son",
    "nomineeDob": "1992-12-13",
    "familyMember": "S.Gowthaman",
    "familyRelation": "Son",
    "familyDob": "1992-12-13",
    "familyAddress": "228,1010 Nesavalar Colony,Mukasipidariyur,Erode.",
    "bankName": "Union Bank of India",
    "accountNo": "747502010002469",
    "ifsc": "UBIN0574759",
    "photo": null
  },
  {
    "id": 7,
    "name": "Palanisamy R",
    "fatherHusbandName": "Ramasamy",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "24/22,Ariyankadu,Kanjikoil,Erode.",
    "qualification": "NA",
    "experience": "1Year",
    "dob": "1957-01-01",
    "doj": "6 Apr , Monday",
    "pan": "GKJPP3491P",
    "aadhar": "776212223909",
    "uan": "",
    "mobile": "7339214743",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Revathi P",
    "nomineeAddress": "24/22,Ariyankadu,Kanjikoil,Erode.",
    "nomineeRelation": "Daughter",
    "nomineeDob": "1984-01-10",
    "familyMember": "Revathi P",
    "familyRelation": "Daughter",
    "familyDob": "1984-01-10",
    "familyAddress": "24/22,Ariyankadu,Kanjikoil,Erode.",
    "bankName": "State Bank of India",
    "accountNo": "34944944455",
    "ifsc": "SBIN0014178",
    "photo": null
  },
  {
    "id": 8,
    "name": "Muthusami P",
    "fatherHusbandName": "Palanisamy",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "226,Chennimalai,1010 Nesavalar Colony,Mukasipidariyur,Erode.",
    "qualification": "8th Std",
    "experience": "2Year",
    "dob": "1967-10-10",
    "doj": "7 Apr , Tuesday",
    "pan": "AVJPM1322R",
    "aadhar": "210538499323",
    "uan": "",
    "mobile": "9842322510",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Maheswari",
    "nomineeAddress": "226,Chennimalai,1010 Nesavalar Colony,Mukasipidariyur,Erode.",
    "nomineeRelation": "Daughter",
    "nomineeDob": "1976-10-20",
    "familyMember": "Maheswari",
    "familyRelation": "Daughter",
    "familyDob": "1976-10-20",
    "familyAddress": "226,Chennimalai,1010 Nesavalar Colony,Mukasipidariyur,Erode.",
    "bankName": "Union Bank of India",
    "accountNo": "747502010002633",
    "ifsc": "UBIN0574759",
    "photo": null
  },
  {
    "id": 9,
    "name": "Senniyappan A",
    "fatherHusbandName": "Ayyavu",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "7,Chidambarampillai Veethi,Chennimalai,Erode.",
    "qualification": "5th std",
    "experience": "6 month",
    "dob": "1964-02-15",
    "doj": "9 Apr , Thursday",
    "pan": "JJFPS4794J",
    "aadhar": "987813676459",
    "uan": "",
    "mobile": "9488481267",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Deviga",
    "nomineeAddress": "7,Chidambarampillai Veethi,Chennimalai,Erode.",
    "nomineeRelation": "Wife",
    "nomineeDob": "1966-01-09",
    "familyMember": "Deviga",
    "familyRelation": "Wife",
    "familyDob": "1966-01-09",
    "familyAddress": "7,Chidambarampillai Veethi,Chennimalai,Erode.",
    "bankName": "Indian Overseas Bank",
    "accountNo": "267201000020848",
    "ifsc": "IOBA0002672",
    "photo": null
  },
  {
    "id": 10,
    "name": "Jothilingam",
    "fatherHusbandName": "Komaran",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "206,North Colony,Kollathupalayam,Pandiampalayam,Erode.",
    "qualification": "8th Std",
    "experience": "1year",
    "dob": "1976-04-01",
    "doj": "9 Apr , Thursday",
    "pan": "BVLPJ9982M",
    "aadhar": "385994279242",
    "uan": "",
    "mobile": "8675261353",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Logeswari",
    "nomineeAddress": "206,North Colony,Kollathupalayam,Pandiampalayam,Erode.",
    "nomineeRelation": "Wife",
    "nomineeDob": "",
    "familyMember": "Logeswari",
    "familyRelation": "Wife",
    "familyDob": "",
    "familyAddress": "206,North Colony,Kollathupalayam,Pandiampalayam,Erode.",
    "bankName": "South Indian Bank",
    "accountNo": "0293053000008944",
    "ifsc": "SIBL0000293",
    "photo": null
  },
  {
    "id": 11,
    "name": "Selvi P",
    "fatherHusbandName": "Palanisamy",
    "gender": "Female",
    "maritalStatus": "Married",
    "address": "4/151,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "qualification": "NA",
    "experience": "2year",
    "dob": "1971-06-09",
    "doj": "7 Apr , Tuesday",
    "pan": "ONFPS2638Q",
    "aadhar": "303592505301",
    "uan": "",
    "mobile": "8973431334",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Palanisamy",
    "nomineeAddress": "4/151,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "nomineeRelation": "Husband",
    "nomineeDob": "",
    "familyMember": "Palanisamy",
    "familyRelation": "Husband",
    "familyDob": "",
    "familyAddress": "4/151,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "bankName": "Canara Bank",
    "accountNo": "3129119000412",
    "ifsc": "CNRB0003129",
    "photo": null
  },
  {
    "id": 12,
    "name": "Maniyal A",
    "fatherHusbandName": "Arumugam",
    "gender": "Female",
    "maritalStatus": "Married",
    "address": "4/162,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "qualification": "NA",
    "experience": "2year",
    "dob": "1970-04-13",
    "doj": "7 Apr , Tuesday",
    "pan": "HVNPM4900C",
    "aadhar": "695214814738",
    "uan": "",
    "mobile": "9095599845",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Arumugam",
    "nomineeAddress": "4/162,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "nomineeRelation": "Husband",
    "nomineeDob": "",
    "familyMember": "Arumugam",
    "familyRelation": "Husband",
    "familyDob": "",
    "familyAddress": "4/162,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "bankName": "Canara Bank",
    "accountNo": "3129119000364",
    "ifsc": "CNRB0003129",
    "photo": null
  },
  {
    "id": 13,
    "name": "Palaniammal S",
    "fatherHusbandName": "",
    "gender": "Female",
    "maritalStatus": "Married",
    "address": "3/55,Arijuna Colony,Periyavirasangili,Perundurai,Erode.",
    "qualification": "NA",
    "experience": "2year",
    "dob": "1973-01-10",
    "doj": "11 Apr, Saturday",
    "pan": "PPBPS7881L",
    "aadhar": "363689959312",
    "uan": "",
    "mobile": "7373029277",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "",
    "nomineeAddress": "3/55,Arijuna Colony,Periyavirasangili,Perundurai,Erode.",
    "nomineeRelation": "",
    "nomineeDob": "",
    "familyMember": "",
    "familyRelation": "",
    "familyDob": "",
    "familyAddress": "3/55,Arijuna Colony,Periyavirasangili,Perundurai,Erode.",
    "bankName": "Union Bank of India",
    "accountNo": "403102011007479",
    "ifsc": "UBIN0540315",
    "photo": null
  },
  {
    "id": 14,
    "name": "Pushpa M",
    "fatherHusbandName": "Manokaran",
    "gender": "Female",
    "maritalStatus": "Married",
    "address": "135,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "qualification": "8th Std",
    "experience": "2year",
    "dob": "1979-05-08",
    "doj": "7 Apr , Tuesday",
    "pan": "GGHPP1778M",
    "aadhar": "786839887361",
    "uan": "",
    "mobile": "9751522099",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Jeevanantham",
    "nomineeAddress": "135,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "nomineeRelation": "Son",
    "nomineeDob": "1998-10-28",
    "familyMember": "Jeevanantham",
    "familyRelation": "Son",
    "familyDob": "1998-10-28",
    "familyAddress": "135,Neikkaranpalayam,Alambadi,Kangeyam,Erode.",
    "bankName": "Canara Bank",
    "accountNo": "3129108001467",
    "ifsc": "CNRB0003129",
    "photo": null
  },
  {
    "id": 15,
    "name": "Devi M",
    "fatherHusbandName": "Murugan",
    "gender": "Female",
    "maritalStatus": "Married",
    "address": "57,Kaasupillam palayam,Kambilliyampatti,Perundurai,Erode.",
    "qualification": "8th Std",
    "experience": "6month",
    "dob": "1987-12-23",
    "doj": "25 Apr, Saturday",
    "pan": "EWBPD9660N",
    "aadhar": "501145508542",
    "uan": "",
    "mobile": "9361228844",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Murugan",
    "nomineeAddress": "57,Kaasupillam palayam,Kambilliyampatti,Perundurai,Erode.",
    "nomineeRelation": "Husband",
    "nomineeDob": "1975-07-16",
    "familyMember": "Murugan",
    "familyRelation": "Husband",
    "familyDob": "1975-07-16",
    "familyAddress": "57,Kaasupillam palayam,Kambilliyampatti,Perundurai,Erode.",
    "bankName": "State Bank of India",
    "accountNo": "43053069392",
    "ifsc": "SBIN0021741",
    "photo": null
  },
  {
    "id": 16,
    "name": "K Jothimani",
    "fatherHusbandName": "Karuppusamy",
    "gender": "Female",
    "maritalStatus": "Married",
    "address": "SNO31,Kasipillampalayam,Kambaliyampatti,Erode.",
    "qualification": "NA",
    "experience": "6month",
    "dob": "1982-08-12",
    "doj": "25 Apr, Saturday",
    "pan": "AUWPJ5133H",
    "aadhar": "804750171293",
    "uan": "",
    "mobile": "9385988353",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Karuppasamy",
    "nomineeAddress": "SNO31,Kasipillampalayam,Kambaliyampatti,Erode.",
    "nomineeRelation": "Husband",
    "nomineeDob": "",
    "familyMember": "Karuppasamy",
    "familyRelation": "Husband",
    "familyDob": "",
    "familyAddress": "SNO31,Kasipillampalayam,Kambaliyampatti,Erode.",
    "bankName": "Indian Overseas Bank",
    "accountNo": "183201000017566",
    "ifsc": "IOBA0001832",
    "photo": null
  },
  {
    "id": 17,
    "name": "Jothi P",
    "fatherHusbandName": "Palanisamy",
    "gender": "Female",
    "maritalStatus": "Married",
    "address": "81/1 Pudhupalayam,Ichipalayam,Uthukuli,Tirupur,638751",
    "qualification": "NA",
    "experience": "1Year",
    "dob": "1971-02-19",
    "doj": "27 Apr,Monday",
    "pan": "BJRPJ8329L",
    "aadhar": "314623968744",
    "uan": "",
    "mobile": "9585349765",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Palanisamy",
    "nomineeAddress": "81/1 Pudhupalayam,Ichipalayam,Uthukuli,Tirupur,638751",
    "nomineeRelation": "Husband",
    "nomineeDob": "1966-10-02",
    "familyMember": "Palanisamy",
    "familyRelation": "Husband",
    "familyDob": "1966-10-02",
    "familyAddress": "81/1 Pudhupalayam,Ichipalayam,Uthukuli,Tirupur,638751",
    "bankName": "Bank of Baroda",
    "accountNo": "5500100011722",
    "ifsc": "BARB0UTTUKU",
    "photo": null
  },
  {
    "id": 18,
    "name": "Palanisamy K",
    "fatherHusbandName": "Kittan",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "81/1 Pudhupalayam,Ichipalayam,Uthukuli,Tirupur,638751",
    "qualification": "NA",
    "experience": "1Year",
    "dob": "1966-10-02",
    "doj": "27 Apr,Monday",
    "pan": "DQPPP6355B",
    "aadhar": "817761448522",
    "uan": "",
    "mobile": "8300462252",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Jothi P",
    "nomineeAddress": "81/1 Pudhupalayam,Ichipalayam,Uthukuli,Tirupur,638751",
    "nomineeRelation": "Wife",
    "nomineeDob": "1971-02-19",
    "familyMember": "Jothi P",
    "familyRelation": "Wife",
    "familyDob": "1971-02-19",
    "familyAddress": "81/1 Pudhupalayam,Ichipalayam,Uthukuli,Tirupur,638751",
    "bankName": "Bank of Baroda",
    "accountNo": "5500100015776",
    "ifsc": "BARB0UTTUKU",
    "photo": null
  },
  {
    "id": 19,
    "name": "Ramasamy P",
    "fatherHusbandName": "Pongiannagounder",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "4/42,Kangirasampudhur,ceenapuram,erode,638057",
    "qualification": "5th std",
    "experience": "6month",
    "dob": "1969-10-03",
    "doj": "26,Apr,Sunday",
    "pan": "",
    "aadhar": "551736880733",
    "uan": "",
    "mobile": "9677477699",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "",
    "nomineeAddress": "4/42,Kangirasampudhur,ceenapuram,erode,638057",
    "nomineeRelation": "",
    "nomineeDob": "",
    "familyMember": "",
    "familyRelation": "",
    "familyDob": "",
    "familyAddress": "4/42,Kangirasampudhur,ceenapuram,erode,638057",
    "bankName": "State Bank of India",
    "accountNo": "20283846392",
    "ifsc": "SBIN0010484",
    "photo": null
  },
  {
    "id": 20,
    "name": "Sivakumar R",
    "fatherHusbandName": "Ramadoss",
    "gender": "Male",
    "maritalStatus": "Married",
    "address": "563/1 meenavar street,kameswaram,kilvelur taluk,nagapattinam,611110",
    "qualification": "SSLC",
    "experience": "1Year",
    "dob": "1980-06-19",
    "doj": "28,Apr,Tuesday",
    "pan": "FOQPR0060Q",
    "aadhar": "238283189970",
    "uan": "",
    "mobile": "8883146491",
    "email": "",
    "esiRegNo": "",
    "nomineeName": "Akash S",
    "nomineeAddress": "563/1 meenavar street,kameswaram,kilvelur taluk,nagapattinam,611110",
    "nomineeRelation": "Son",
    "nomineeDob": "2004-03-17",
    "familyMember": "",
    "familyRelation": "",
    "familyDob": "2004-03-17",
    "familyAddress": "563/1 meenavar street,kameswaram,kilvelur taluk,nagapattinam,611110",
    "bankName": "Karur Vysya Bank",
    "accountNo": "116715500014972",
    "ifsc": "KVBL0001167",
    "photo": null
  }
];
